- time:
    hour: 7
    minute: 30
    second: 0
  commands:
  - command: a.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 7
    minute: 38
    second: 0
  commands:
  - command: 1.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 7
    minute: 48
    second: 0
  commands:
  - command: 1.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 7
    minute: 50
    second: 0
  commands:
  - command: 2.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 8
    minute: 30
    second: 0
  commands:
  - command: 3.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 8
    minute: 38
    second: 0
  commands:
  - command: 1.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 8
    minute: 40
    second: 0
  commands:
  - command: 2.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 9
    minute: 20
    second: 0
  commands:
  - command: 3.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 9
    minute: 28
    second: 0
  commands:
  - command: 1.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 9
    minute: 30
    second: 0
  commands:
  - command: 2.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 10
    minute: 10
    second: 0
  commands:
  - command: 3.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 10
    minute: 10
    second: 30
  commands:
  - command: 4.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 10
    minute: 23
    second: 0
  commands:
  - command: 1.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 10
    minute: 25
    second: 0
  commands:
  - command: 2.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 11
    minute: 5
    second: 0
  commands:
  - command: 3.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 11
    minute: 13
    second: 0
  commands:
  - command: 1.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 11
    minute: 15
    second: 0
  commands:
  - command: 2.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 11
    minute: 55
    second: 0
  commands:
  - command: 3.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 13
    minute: 58
    second: 0
  commands:
  - command: 1.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 14
    minute: 0
    second: 0
  commands:
  - command: 2.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 14
    minute: 40
    second: 0
  commands:
  - command: 3.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 14
    minute: 48
    second: 0
  commands:
  - command: 1.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 14
    minute: 50
    second: 0
  commands:
  - command: 2.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 15
    minute: 30
    second: 0
  commands:
  - command: 3.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 15
    minute: 30
    second: 30
  commands:
  - command: 4.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 15
    minute: 43
    second: 0
  commands:
  - command: 1.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 15
    minute: 45
    second: 0
  commands:
  - command: 2.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 16
    minute: 25
    second: 0
  commands:
  - command: 3.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 16
    minute: 33
    second: 0
  commands:
  - command: 1.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 16
    minute: 35
    second: 0
  commands:
  - command: 2.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 17
    minute: 15
    second: 0
  commands:
  - command: 3.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 19
    minute: 0
    second: 0
  commands:
  - command: 2.mp3
    parameters: ''
    audio: true
    notify: 30
- time:
    hour: 21
    minute: 0
    second: 0
  commands:
  - command: 3.mp3
    parameters: ''
    audio: true
    notify: 30
