[package]
name = "boom_you_up_r"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = "0"
rodio = "0"
notify-rust = "4"
time = { version = "0", features = ["local-offset"] }
opener = { path = "libs/opener" }

#[target.'cfg(windows)'.dependencies.windows]
#version = "0"
#features = [
#    "Win32_Foundation",
#    "Win32_System_Diagnostics_Debug",
#    "Win32_System_SystemInformation",
#    "Win32_UI_Shell",
#    "Win32_UI_WindowsAndMessaging"
#]
