on:
  - push
  - pull_request

name: Build

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - aarch64-pc-windows-msvc
        type:
          - release
          - debug
        include:
          - cross: true
          - target: x86_64-pc-windows-msvc
            cross: false
          - type: release
            type-name: Release
            arg: ' --release'
          - type: debug
            type-name: Debug
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: Change version
        run: |
          cargo install cargo-edit
          cargo set-version -m ${{ github.sha }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --verbose --target ${{ matrix.target }}${{ matrix.arg }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-${{ matrix.type-name }}-${{ github.sha }}
          path: target/${{ matrix.target }}/${{ matrix.type }}/boom_you_up_r*
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
        type:
          - release
          - debug
        include:
          - cross: true
          - target: x86_64-unknown-linux-gnu
            cross: false
          - type: release
            type-name: Release
            arg: ' --release'
          - type: debug
            type-name: Debug
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: Change version
        run: |
          cargo install cargo-edit
          cargo set-version -m ${{ github.sha }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --verbose --target ${{ matrix.target }}${{ matrix.arg }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-${{ matrix.type-name }}-${{ github.sha }}
          path: target/${{ matrix.target }}/${{ matrix.type }}/boom_you_up_r*
  build-macos:
    name: Build MacOS
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
        type:
          - release
          - debug
        include:
          - cross: true
          - target: x86_64-apple-darwin
            cross: false
          - type: release
            type-name: Release
            arg: ' --release'
          - type: debug
            type-name: Debug
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: Change version
        run: |
          cargo install cargo-edit
          cargo set-version -m ${{ github.sha }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --verbose --target ${{ matrix.target }}${{ matrix.arg }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-${{ matrix.type-name }}-${{ github.sha }}
          path: target/${{ matrix.target }}/${{ matrix.type }}/boom_you_up_r*
