on:
  - push
  - pull_request

name: Build

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        type: [Debug, Release]
        include:
          - type: Debug
            path: debug
          - type: Release
            path: release
            arg: ' --release'
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target }}${{ matrix.arg }} --verbose
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-${{ matrix.type }}
          path: target/${{ matrix.target }}/${{ matrix.path }}/boom_you_up_r*